### ISSUE TITLE
Inference does not work without --full flag

### ISSUE THREAD

**Issue by francois-drielsma** [Temigo/uresnet_pytorch#2]
Within the inference_loop(flags, handlers) function, the print functions raise an error.

Here's the command I run:
`python bin/uresnet.py inference -mp weights/snapshot-2999.ckpt -io larcv_sparse -bs 1 --gpus 0 -nc 5 -rs 1 -ss 512 -dd 3 -uns 5 -uf 16 -dkeys data,fivetypes -mn uresnet_sparse -it 100 -ld log -if '/gpfs/slac/staas/fs1/g/neutrino/kterao/data/dlprod_ppn_v10/shower_relabel/dlprod_512px_09.root'
`
Here's the error:
```
Traceback (most recent call last):
  File "bin/uresnet.py", line 14, in <module>
    main()
  File "bin/uresnet.py", line 11, in main
    flags.parse_args()
  File "/u/nu/drielsma/uresnet/uresnet_pytorch/uresnet/flags.py", line 153, in parse_args
    args.func(self)
  File "/u/nu/drielsma/uresnet/uresnet_pytorch/uresnet/main_funcs.py", line 56, in inference
    inference_loop(flags, handlers)
  File "/u/nu/drielsma/uresnet/uresnet_pytorch/uresnet/main_funcs.py", line 242, in inference_loop
    np.unique(np.argmax(res['segmentation'][0], axis=0)[(data_blob['data'][0]>0)[0, 0, ...]], return_counts=True),
TypeError: 'bool' object has no attribute '__getitem__'
```

NB: `data_blob['data'][0]>0` is `bool`

**Comment by Temigo** [comment]
Yes sorry, I meant to remove the "simple" inference long time ago. It should just be replaced by full inference function. (without needing to put `--full` option). On the todo list, thanks for reminding me!

**Comment by francois-drielsma** [comment]
No worries, thank you!
